name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pylint
          pip install mypy
          pip install -r src/requirements.txt

      - name: Lint
        run: pylint src/ --errors-only --disable=E0401,E0602

      - name: Type Check
        run: mypy src/
